# -*- coding: utf-8 -*-
"""Data Preparation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eVhZ0BjhFKmald-7FHfe5thGjFXgVkF1
"""

from google.colab import files
data=files.upload()

"""# Explonatory Data Analysis"""

import pandas as pd

data = pd.read_csv('measles - measles.csv')

display(data)

data.info

data.describe()

"""no values in district column"""

data_cleaned = data.drop(columns=['district'])

data_cleaned.dtypes

"""Year data type should be numeric"""

data_cleaned['year'] = data_cleaned['year'].str.split('-').str[0]
data_cleaned['year'] = pd.to_numeric(data_cleaned['year'], errors='coerce')

data_cleaned.drop(columns=['index'], inplace=True)

print(data_cleaned)

data_cleaned.isnull().sum()

"""Replace missing values in columns type,city,county  with unkown and xmed,xper,xrel,enroll with 0 ,Long lat missing values can be ignored"""

data_cleaned['type'].fillna('Unknown', inplace=True)
data_cleaned['city'].fillna('Unknown', inplace=True)
data_cleaned['county'].fillna('Unknown', inplace=True)

data_cleaned['xmed'].fillna(0, inplace=True)
data_cleaned['xper'].fillna(0, inplace=True)
data_cleaned['xrel'].fillna(0, inplace=True)

data_cleaned['enroll'].fillna(0, inplace=True)

data_cleaned.duplicated().sum()

"""delete duplicated records by keeping first occurence"""

data_cleaned = data_cleaned.drop_duplicates(keep='first')

print(data_cleaned)

data_cleaned.to_csv('Prepared_data.csv')